server:
  port: 4004 # Gateway listens on port 4004

spring:
  cloud:
    gateway:
      routes:

        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/** #This line means:If incoming request starts with /auth/, this route should handle it.
          filters:
            - StripPref=1 #This line means:Remove the first path segment before forwarding.

#If request is:localhost:4004/auth/validate/token
#After StripPrefix=1:
#  /validate/token
#Forwarded to:http://auth-service:4005/validate/token


        # =========================================================
        # PATIENT SERVICE ROUTE
        # =========================================================
        #
        # CLIENT REQUEST FLOW:
        #
        # REST CLIENT / FRONTEND:
        # http://localhost:4004/api/patients
        #
        # Request first lands on:
        # --> API Gateway
        #
        # API Gateway checks all configured routes and
        # matches the request using the Predicate rule below:
        #
        # Path=/api/patients/**
        #
        # Once matched, Gateway forwards the request to:
        # --> http://patient-service:4000
        #
        # FILTER:
        # StripPrefix=1
        #
        # This removes the first path segment:
        #
        # BEFORE:
        # /api/patients
        #
        # AFTER:
        # /patients
        #
        # Final forwarded request becomes:
        # --> http://patient-service:4000/patients
        #
        # Now the Patient Service Spring Boot application
        # receives the request and its controller handles:
        #
        # @RequestMapping("/patients")
        #
        # So API Gateway acts like a traffic controller /
        # reverse proxy between client and microservices.
        #
        # =========================================================

        - id: patient-service-route
          uri: http://patient-service:4000

          predicates:
            - Path=/api/patients/**

          filters:
            - StripPrefix=1
            - JwtValidation
#By putting JwtValidation above we make sure that the patient service is not directly accessed unless the
#request goes through the API Gateway and that the token validation proves that the token is valid and has come from
#our Auth service.


        # =========================================================
        # SWAGGER / OPENAPI DOCS ROUTE
        # =========================================================
        #
        # CLIENT REQUEST:
        # http://localhost:4004/api-docs/patients
        #
        # API Gateway receives this request and forwards it to:
        #
        # http://patient-service:4000/v3/api-docs
        #
        # FILTER:
        # RewritePath
        #
        # This rewrites:
        #
        # BEFORE:
        # /api-docs/patients
        #
        # AFTER:
        # /v3/api-docs
        #
        # This is useful because:
        #
        # - Clients should not directly call microservices
        # - API Gateway becomes the single entry point
        # - Swagger docs of all microservices can be exposed
        #   through one unified gateway
        #
        # =========================================================

        - id: api-docs-patient-route
          uri: http://patient-service:4000

          predicates:
            - Path=/api-docs/patients

          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        - id: api-docs-auth-route
          uri : http://auth-service:4005
        - predicates:
              - Path=/api-docs/auth
          filters:
           -RewritePath=/api-docs/auth,/v3/api-docs


