spring.application.name=patient-service

#UNCOMMENT BELOW TO USE IN-MEMORY DB OUTSIDE OF DOCKER
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=admin_viewer
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always

#above makes sure our db is always in sync with our Patient Entity
server.port=4000
#For All our microservices we will have under 4k range like 4001 , 4002, and so on,
# just a convention we are following here.

logging.level.root=info
#Above means we are telling our Spring app that we need all the info. warn and error messages
#be logged to the terminal or console
